### ISSUE TITLE
To-do List For 2.0.1

### ISSUE THREAD

**Issue by nfls** [OSCStudio/nitic#1]
- Add Supporting For Currency 
- [x] Creating money types
- [ ] Deleting money types
- [x] Updating currency list
- [ ] Trading
-  Add More Functions For User Center
- [ ] Banning users
- [ ] Creating large amount of users
- [ ] Editing one user's profile/money
- [ ] More user types
